#!/usr/bin/env bash

function mkd() {
  mkdir -p "$@" && cd "$_";
}

function gbr() {
  local branch
  branch=$(git branch -a | fzf $([ $# -eq 0 ] || echo --query $1))

  if [[ -n $branch ]]
  then
    git switch $(echo $branch | xargs)
  fi
}

function ts() {
  if [[ $# -eq 1 ]]; then
    selected=$1
  else
    selected=$(find ~/dev -mindepth 1 -maxdepth 1 -type d | fzf)
  fi

  if [[ -z $selected ]]; then
    return 0
  fi

  selected_name=$(basename "$selected" | tr . _)
  tmux_running=$(pgrep tmux)

  if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    return 0
  fi

  if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
  fi

  if [[ -z $TMUX ]]; then
    tmux attach-session -t $selected_name
  else
    tmux switch-client -t $selected_name
  fi
}

function s() {
  local file
  file=$(ls ~/.config/tmux/sessions/ | fzf)

  if [[ -n $file ]]; then
    bash ~/.config/tmux/sessions/$file
  fi
}
